#!/usr/bin/env python
from NuPost import NuPost
import sys, time
import socket
import os

def main(host, port):
    post = NuPost(host, port)

    cmd = sys.argv[1]
    if cmd == "go":
        n = int(sys.argv[3]) if len(sys.argv) == 4 else None
        post.go(sys.argv[2], n)
    elif cmd == "stop":
        post.stop()
    elif cmd == "setrun":
        post.set_run_num(int(sys.argv[2]))
    elif cmd == "status":
        post.status()
    elif cmd == "monitor":
        while 1:
            rate = post.get_tape_rate()
            sys.stdout.write("%d kB (%d blocks)\r" % (rate['kbytes'], rate['block']))
            sys.stdout.flush()
            time.sleep(1)
    elif cmd == "help":
        print "go <prefix>      Start new file called prefix"
        print "stop             Stop running file"
        print "status           Print ACQ status"
        print "monitor          Monitor data rate"
        print "help             Print this"
    else:
        print "Unknown command: %s" % cmd


if __name__ == "__main__":
    # If we run on pcids03 then we do not need to make a tunnel                                        

    if socket.gethostname().startswith("pcids03"):
        main("nnids1", 8015)
    else:
        from sshtunnel import SSHTunnelForwarder

	password = os.environ.get('NUTAQ_PASS')
        if password is None:
            print "Missing password for pcids03"
            exit(1)

	with SSHTunnelForwarder(
                ('pcids03', 22),
                ssh_username="upcids03",
                ssh_password=password,
                remote_bind_address=('nnids1', 8015)
        ) as server:
            main("localhost", server.local_bind_port)
